/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { MatchResults } from "@stencil/router";
export namespace Components {
    interface AppHome {
    }
    interface AppProfile {
        "match": MatchResults;
    }
    interface AppRoot {
    }
    interface PictureGallery {
        "images": string;
    }
    interface TabContainer {
    }
    interface TabContent {
        "titleText": string;
    }
}
declare global {
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {
    }
    var HTMLAppProfileElement: {
        prototype: HTMLAppProfileElement;
        new (): HTMLAppProfileElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLPictureGalleryElement extends Components.PictureGallery, HTMLStencilElement {
    }
    var HTMLPictureGalleryElement: {
        prototype: HTMLPictureGalleryElement;
        new (): HTMLPictureGalleryElement;
    };
    interface HTMLTabContainerElement extends Components.TabContainer, HTMLStencilElement {
    }
    var HTMLTabContainerElement: {
        prototype: HTMLTabContainerElement;
        new (): HTMLTabContainerElement;
    };
    interface HTMLTabContentElement extends Components.TabContent, HTMLStencilElement {
    }
    var HTMLTabContentElement: {
        prototype: HTMLTabContentElement;
        new (): HTMLTabContentElement;
    };
    interface HTMLElementTagNameMap {
        "app-home": HTMLAppHomeElement;
        "app-profile": HTMLAppProfileElement;
        "app-root": HTMLAppRootElement;
        "picture-gallery": HTMLPictureGalleryElement;
        "tab-container": HTMLTabContainerElement;
        "tab-content": HTMLTabContentElement;
    }
}
declare namespace LocalJSX {
    interface AppHome {
    }
    interface AppProfile {
        "match"?: MatchResults;
    }
    interface AppRoot {
    }
    interface PictureGallery {
        "images"?: string;
    }
    interface TabContainer {
    }
    interface TabContent {
        "titleText"?: string;
    }
    interface IntrinsicElements {
        "app-home": AppHome;
        "app-profile": AppProfile;
        "app-root": AppRoot;
        "picture-gallery": PictureGallery;
        "tab-container": TabContainer;
        "tab-content": TabContent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-profile": LocalJSX.AppProfile & JSXBase.HTMLAttributes<HTMLAppProfileElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "picture-gallery": LocalJSX.PictureGallery & JSXBase.HTMLAttributes<HTMLPictureGalleryElement>;
            "tab-container": LocalJSX.TabContainer & JSXBase.HTMLAttributes<HTMLTabContainerElement>;
            "tab-content": LocalJSX.TabContent & JSXBase.HTMLAttributes<HTMLTabContentElement>;
        }
    }
}
